'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8825
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ex1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10001_grinning_face_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10001-grinning-face-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_computer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-computer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_doctor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-doctor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_doctor_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-doctor-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_dropper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-dropper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_flask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-flask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_flask1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-flask1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_fracture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-fracture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_hospital() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-hospital", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_hospital1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-hospital1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_hospital2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-hospital2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_medical_history_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-medical-history-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_nurse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-nurse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_nurse_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-nurse-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_patient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-patient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_patient1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-patient1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _101_visibility() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("101-visibility", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ahos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ahos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property architecture_daylight_door_239853() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("architecture-daylight-door-239853", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property atomic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atomic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blur_door_factory_451() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blur-door-factory-451", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blur_door_factory_4511() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blur-door-factory-4511", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bright_cardiac_cardiology_433267() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bright-cardiac-cardiology-433267", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Close_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button-Close-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Delete_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button-Delete-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_delete_icon__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button-delete-icon (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Help_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button-Help-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Info_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button-Info-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Previous_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button-Previous-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Reload_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button-Reload-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Turn_Off_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button-Turn-Off-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardiogram_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardiogram-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eye() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eye", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eye1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eye1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heart_2211180_1920() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart-2211180_1920", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heartbeat_163709_1280() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartbeat-163709_1280", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hospital() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hospital", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hospital_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hospital-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hospital_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hospital-11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hospital_ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hospital.ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hospital1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hospital1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hospital2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hospital2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medical_1617364_1920() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medical-1617364_1920", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medical_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medical copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property microscope() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("microscope", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property notepad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notepad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OSZB6Y0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OSZB6Y0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
